### ISSUE TITLE
Support node arguments

### ISSUE THREAD

**Issue by DonovanCharpin** [DiegoZoracKy/magicli#1]
Thank you for this really useful library!

After our discussion on the medium article, I would like to know if it would be possible to support node arguments like --inspect. This one is really important because I want to debug my node server in dev mode.

``` js
magicli server.js server --inspect
```

I think it would be really interesting for several usages!

What do you think?

**Comment by DiegoZoracKy** [comment]
Hi @DonovanCharpin,

Yes, your suggestion makes totally sense. I'll try to take a look at that on the following days.

Thanks one more time for your feedback.

**Comment by DonovanCharpin** [comment]
Great @DiegoZoracKy, thank you so much for considering this suggestion!

**Comment by DiegoZoracKy** [comment]
@DonovanCharpin thinking of what you want to accomplish, I believe there is a solution already. I noticed that you are using the global version of MagiCLI, however you could instead use it as a dependency from your module. By doing that you would be able to call it from the terminal using `node` passing in any arguments for it.

I don't know if the **server.js** on your example is already a module, containing a package.json. Assuming that it is not, you just have to:

**1. Create a directory for the module.**

Let's call the directory as **my-server** for the example. Create it and move your **server.js** to it.

**2. Create a file to be used as a cli.**

For example, create the file **cli.js** (inside **my-server**) having the following content:

```javascript
#!/usr/bin/env node

require('magicli')();
```

More info here: https://github.com/DiegoZoracKy/magicli#usage-the-most-simple-and-minimal-way

**3. Create a package.json having magicli as a dependency**

```javascript
{
  "name": "my-server",
  "version": "0.0.1",
  "description": "",
  "bin": "cli.js",
  "main": "server.js",
  "dependencies": {
    "magicli": "^0.1.2"
  }
}
```
The final dir structure should be:

```
- my-server/
  - cli.js  
  - server.js
  - package.json
```

Having that you can now execute it as:

```bash
node --inspect my-server/cli.js server 
```

Tell me if that worked well for you.

**Comment by DonovanCharpin** [comment]
Hi @DiegoZoracKy !

Thanks!

So I'm already using magicli in my project. The `magicli server.js server --inspect` is from my package.json. I would like not having to create another file cli.js because I have already so many files of config (babel, eslint, .env, dockerfile, jenkins etc). It would be just easier to be able to use the default node arguments along the magicli command.

**Comment by DiegoZoracKy** [comment]
I've got your point. Currently under the hood I'm not opening a child
process and executing `node` from the terminal. If I were doing that It
would be easier to just grab arguments after the end of options and pass
them to `node`. In the end it is being executed as we usually do with other
CLIs, via shebang.

To not have to bloat our current simple execution process, I would say that
it would be easier for you to create that extra cli file. In the end, as
you already have it installed, you have just to include the bin property on
package.json. What do you think?

**Comment by DiegoZoracKy** [comment]
Hi @DonovanCharpin,

Do you have some news about this?

**Comment by DonovanCharpin** [comment]
Hi @DiegoZoracKy 

Thanks for the follow-up! Yes I'll modify the way I use magicli when I'll find some time. Thanks for the solution!

**Comment by DiegoZoracKy** [comment]
Great! Thanks!
